name: al_hadith
description: "Al Hadith in 9 Languages with all major Hadith Collections"

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  go_router: ^17.1.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  archive: ^4.0.7
  google_fonts: ^8.0.1
  intl: ^0.20.2
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.10.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/all_hadith_info.json
